[E 240212 11:40:35 smartConnect:320] API request failed: {'message': 'Invalid Order Type', 'errorcode': 'AB1020', 'status': False, 'data': None}
[E 240212 17:15:15 operations:85] Error fetching historical data: We don't support other than BANKNIFTY & NIFTY 50
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 52, in get_index_info
        raise ValueError("We don't support other than BANKNIFTY & NIFTY 50")
    ValueError: We don't support other than BANKNIFTY & NIFTY 50
[E 240212 17:15:23 operations:85] Error fetching historical data: We don't support other than BANKNIFTY & NIFTY 50
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 52, in get_index_info
        raise ValueError("We don't support other than BANKNIFTY & NIFTY 50")
    ValueError: We don't support other than BANKNIFTY & NIFTY 50
[E 240212 17:15:32 operations:85] Error fetching historical data: We don't support other than BANKNIFTY & NIFTY 50
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 52, in get_index_info
        raise ValueError("We don't support other than BANKNIFTY & NIFTY 50")
    ValueError: We don't support other than BANKNIFTY & NIFTY 50
[E 240212 17:16:21 operations:85] Error fetching historical data: We don't support other than BANKNIFTY & NIFTY(50)
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 52, in get_index_info
        raise ValueError("We don't support other than BANKNIFTY & NIFTY(50)")
    ValueError: We don't support other than BANKNIFTY & NIFTY(50)
[E 240212 17:29:07 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:29:24 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:29:40 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:29:56 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:29:59 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:30:28 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
[E 240212 17:30:35 operations:105] Error fetching historical data: We don't support other than 10AM & 1PM (13) time
    Traceback (most recent call last):
      File "c:\Users\user\Documents\angleOne_trading\operations.py", line 62, in get_index_info
        raise ValueError("We don't support other than 10AM & 1PM (13) time")
    ValueError: We don't support other than 10AM & 1PM (13) time
